/**
 * Export utilities for copying and downloading analysis results
 */

/**
 * Copy text to clipboard
 * @param {string} text - Text to copy
 * @returns {Promise<boolean>} - Success status
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
}

/**
 * Format 7-day plan as plain text
 * @param {Array} plan - 7-day plan array
 * @returns {string} - Formatted text
 */
export function formatPlanAsText(plan) {
  let text = '📅 7-DAY PREPARATION PLAN\n';
  text += '=' .repeat(50) + '\n\n';
  
  plan.forEach(day => {
    text += `Day ${day.day}: ${day.title}\n`;
    text += '-'.repeat(30) + '\n';
    day.tasks.forEach(task => {
      text += `• ${task}\n`;
    });
    text += '\n';
  });
  
  return text;
}

/**
 * Format checklist as plain text
 * @param {Object} checklist - Round-wise checklist
 * @returns {string} - Formatted text
 */
export function formatChecklistAsText(checklist) {
  let text = '✅ ROUND-WISE CHECKLIST\n';
  text += '=' .repeat(50) + '\n\n';
  
  Object.values(checklist).forEach(round => {
    text += `${round.title}\n`;
    text += '-'.repeat(30) + '\n';
    round.items.forEach(item => {
      text += `[ ] ${item}\n`;
    });
    text += '\n';
  });
  
  return text;
}

/**
 * Format questions as plain text
 * @param {Array} questions - Interview questions array
 * @returns {string} - Formatted text
 */
export function formatQuestionsAsText(questions) {
  let text = '❓ LIKELY INTERVIEW QUESTIONS\n';
  text += '=' .repeat(50) + '\n\n';
  
  questions.forEach((question, idx) => {
    text += `${idx + 1}. ${question}\n\n`;
  });
  
  return text;
}

/**
 * Generate full analysis report as TXT
 * @param {Object} analysis - Full analysis object
 * @returns {string} - Complete report text
 */
export function generateFullReport(analysis) {
  const { company, role, readinessScore, extractedSkills, plan, checklist, questions, skillConfidenceMap } = analysis;
  
  let report = '';
  
  // Header
  report += 'PLACEMENT READINESS ANALYSIS REPORT\n';
  report += '=' .repeat(60) + '\n\n';
  
  // Company & Role
  if (company || role) {
    report += '🏢 JOB DETAILS\n';
    report += '-'.repeat(30) + '\n';
    if (company) report += `Company: ${company}\n`;
    if (role) report += `Role: ${role}\n`;
    report += '\n';
  }
  
  // Readiness Score
  report += `📊 READINESS SCORE: ${readinessScore}/100\n`;
  report += '-'.repeat(30) + '\n';
  if (readinessScore >= 80) report += 'Status: Well Prepared ✅\n';
  else if (readinessScore >= 60) report += 'Status: Good Progress 📈\n';
  else report += 'Status: Needs Preparation ⚠️\n';
  report += '\n';
  
  // Skills
  report += '🎯 EXTRACTED SKILLS\n';
  report += '-'.repeat(30) + '\n';
  
  if (extractedSkills.general) {
    report += `${extractedSkills.general[0]}\n`;
  } else {
    Object.values(extractedSkills).forEach(category => {
      report += `\n${category.label}:\n`;
      category.skills.forEach(skill => {
        const confidence = skillConfidenceMap?.[skill] || 'practice';
        const status = confidence === 'know' ? '✓' : '○';
        report += `  ${status} ${skill} (${confidence === 'know' ? 'Know' : 'Need Practice'})\n`;
      });
    });
  }
  report += '\n';
  
  // 7-Day Plan
  report += formatPlanAsText(plan);
  report += '\n';
  
  // Checklist
  report += formatChecklistAsText(checklist);
  report += '\n';
  
  // Questions
  report += formatQuestionsAsText(questions);
  
  // Footer
  report += '\n' + '=' .repeat(60) + '\n';
  report += 'Generated by Placement Readiness Platform\n';
  report += `Date: ${new Date().toLocaleDateString()}\n`;
  
  return report;
}

/**
 * Download text as file
 * @param {string} text - Text content
 * @param {string} filename - Filename
 */
export function downloadAsFile(text, filename) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
