/**
 * Export utilities for copying and downloading analysis results
 */

/**
 * Copy text to clipboard
 * @param {string} text - Text to copy
 * @returns {Promise<boolean>} - Success status
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
}

/**
 * Format 7-day plan as plain text
 * @param {Array} plan - 7-day plan array (plan7Days)
 * @returns {string} - Formatted text
 */
export function formatPlanAsText(plan) {
  if (!Array.isArray(plan)) return '📅 7-DAY PREPARATION PLAN\nNo plan available.\n';
  
  let text = '📅 7-DAY PREPARATION PLAN\n';
  text += '=' .repeat(50) + '\n\n';
  
  plan.forEach(day => {
    text += `Day ${day.day}: ${day.focus}\n`;
    text += '-'.repeat(30) + '\n';
    day.tasks?.forEach(task => {
      text += `• ${task}\n`;
    });
    text += '\n';
  });
  
  return text;
}

/**
 * Format checklist as plain text
 * @param {Array} checklist - Round-wise checklist array
 * @returns {string} - Formatted text
 */
export function formatChecklistAsText(checklist) {
  if (!Array.isArray(checklist)) return '✅ ROUND-WISE CHECKLIST\nNo checklist available.\n';
  
  let text = '✅ ROUND-WISE CHECKLIST\n';
  text += '=' .repeat(50) + '\n\n';
  
  checklist.forEach(round => {
    text += `${round.roundTitle}\n`;
    text += '-'.repeat(30) + '\n';
    round.items?.forEach(item => {
      text += `[ ] ${item}\n`;
    });
    text += '\n';
  });
  
  return text;
}

/**
 * Format questions as plain text
 * @param {Array} questions - Interview questions array
 * @returns {string} - Formatted text
 */
export function formatQuestionsAsText(questions) {
  if (!Array.isArray(questions)) return '❓ LIKELY INTERVIEW QUESTIONS\nNo questions available.\n';
  
  let text = '❓ LIKELY INTERVIEW QUESTIONS\n';
  text += '=' .repeat(50) + '\n\n';
  
  questions.forEach((question, idx) => {
    text += `${idx + 1}. ${question}\n\n`;
  });
  
  return text;
}

/**
 * Generate full analysis report as TXT
 * @param {Object} analysis - Full analysis object (standardized schema)
 * @returns {string} - Complete report text
 */
export function generateFullReport(analysis) {
  const { 
    company, 
    role, 
    baseScore, 
    finalScore, 
    extractedSkills, 
    plan7Days, 
    checklist, 
    questions, 
    skillConfidenceMap 
  } = analysis;
  
  // Use finalScore if available, otherwise baseScore
  const score = finalScore ?? baseScore ?? 0;
  
  let report = '';
  
  // Header
  report += 'PLACEMENT READINESS ANALYSIS REPORT\n';
  report += '=' .repeat(60) + '\n\n';
  
  // Company & Role
  if (company || role) {
    report += '🏢 JOB DETAILS\n';
    report += '-'.repeat(30) + '\n';
    if (company) report += `Company: ${company}\n`;
    if (role) report += `Role: ${role}\n`;
    report += '\n';
  }
  
  // Readiness Score
  report += `📊 READINESS SCORE: ${score}/100\n`;
  if (baseScore !== undefined) report += `Base Score: ${baseScore}/100\n`;
  report += '-'.repeat(30) + '\n';
  if (score >= 80) report += 'Status: Well Prepared ✅\n';
  else if (score >= 60) report += 'Status: Good Progress 📈\n';
  else report += 'Status: Needs Preparation ⚠️\n';
  report += '\n';
  
  // Skills
  report += '🎯 EXTRACTED SKILLS\n';
  report += '-'.repeat(30) + '\n';
  
  const categoryLabels = {
    coreCS: 'Core Computer Science',
    languages: 'Programming Languages',
    web: 'Web Development',
    data: 'Data & Databases',
    cloud: 'Cloud & DevOps',
    testing: 'Testing',
    other: 'Other Skills'
  };
  
  if (extractedSkills && typeof extractedSkills === 'object') {
    Object.entries(extractedSkills).forEach(([category, skills]) => {
      if (!Array.isArray(skills) || skills.length === 0) return;
      
      report += `\n${categoryLabels[category] || category}:\n`;
      skills.forEach(skill => {
        const confidence = skillConfidenceMap?.[skill] || 'practice';
        const status = confidence === 'know' ? '✓' : '○';
        report += `  ${status} ${skill} (${confidence === 'know' ? 'Know' : 'Need Practice'})\n`;
      });
    });
  }
  report += '\n';
  
  // 7-Day Plan
  report += formatPlanAsText(plan7Days);
  report += '\n';
  
  // Checklist
  report += formatChecklistAsText(checklist);
  report += '\n';
  
  // Questions
  report += formatQuestionsAsText(questions);
  
  // Footer
  report += '\n' + '=' .repeat(60) + '\n';
  report += 'Generated by Placement Readiness Platform\n';
  report += `Date: ${new Date().toLocaleDateString()}\n`;
  
  return report;
}

/**
 * Download text as file
 * @param {string} text - Text content
 * @param {string} filename - Filename
 */
export function downloadAsFile(text, filename) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
